### ISSUE TITLE
"La stagione è chiusa" ma la stagione non è effettivamente chiusa

### ISSUE THREAD

**Issue by nicolello-dev** [FerdinandoLM/BancaDelMeme#5]
Come si può vedere, per esempio, [qui](https://www.reddit.com/r/BancaDelMeme/comments/13jbq7w/basata_su_una_storia_che_vorrei_fosse_vera/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1), il bot dice che la stagione è chiusa seppur non lo sia. Ciononostante, lascia aprire nuovi account e da loro la giusta quantità di MEM$

**Comment by timendum** [comment]
Dovrebbe essere a posto, colpa di alcune componenti che non sono state riavviate e hanno mantenuto la configurazione vecchia, con la stagione ancora chiusa.
